export const ROOM_RULES = {
  entrance: {
    label: '门厅',
    minArea: 3,
    maxArea: 10,
    minWidth: 1.2,
    minDepth: 1.5,
    idealWidthRange: [1.5, 2.4],
    idealDepthRange: [1.8, 2.8],
    maxAspectRatio: 3,
    mustTouchExterior: true,
    preferTouchExterior: true,
    mustConnectTo: ['living_room', 'corridor'],
    preferConnectTo: ['dining'],
    avoidOnlyAccessFrom: [],
    windowRequired: false,
    circulationPriority: 10
  },
  living_room: {
    label: '客厅',
    minArea: 18,
    maxArea: 45,
    minWidth: 3.9,
    minDepth: 4.5,
    idealWidthRange: [4.2, 5.4],
    idealDepthRange: [4.8, 6.2],
    maxAspectRatio: 3,
    mustTouchExterior: false,
    preferTouchExterior: true,
    mustConnectTo: ['stairs'],
    preferConnectTo: ['dining', 'corridor', 'bathroom'],
    avoidOnlyAccessFrom: [],
    windowRequired: true,
    circulationPriority: 10
  },
  dining: {
    label: '餐厅',
    minArea: 6,
    maxArea: 22,
    minWidth: 2.4,
    minDepth: 2.5,
    idealWidthRange: [2.8, 3.8],
    idealDepthRange: [2.6, 4.2],
    maxAspectRatio: 3,
    mustTouchExterior: false,
    preferTouchExterior: true,
    mustConnectTo: [],
    preferConnectTo: ['living_room', 'kitchen'],
    avoidOnlyAccessFrom: [],
    windowRequired: false,
    circulationPriority: 7
  },
  kitchen: {
    label: '厨房',
    minArea: 6,
    maxArea: 16,
    minWidth: 2.1,
    minDepth: 2.8,
    idealWidthRange: [2.4, 3.3],
    idealDepthRange: [2.8, 4.2],
    maxAspectRatio: 3,
    mustTouchExterior: true,
    preferTouchExterior: true,
    mustConnectTo: [],
    preferConnectTo: ['dining', 'living_room'],
    avoidOnlyAccessFrom: [],
    windowRequired: true,
    circulationPriority: 4
  },
  bathroom: {
    label: '卫生间',
    minArea: 4,
    maxArea: 10,
    minWidth: 1.8,
    minDepth: 2.2,
    idealWidthRange: [1.8, 2.4],
    idealDepthRange: [2.2, 3.0],
    maxAspectRatio: 2.5,
    mustTouchExterior: false,
    preferTouchExterior: true,
    mustConnectTo: [],
    preferConnectTo: ['living_room', 'lounge', 'corridor'],
    avoidOnlyAccessFrom: ['kitchen'],
    windowRequired: false,
    circulationPriority: 6
  },
  bedroom: {
    label: '卧室',
    minArea: 9,
    maxArea: 25,
    minWidth: 3.0,
    minDepth: 3.6,
    idealWidthRange: [3.0, 4.2],
    idealDepthRange: [3.6, 4.8],
    maxAspectRatio: 3,
    mustTouchExterior: true,
    preferTouchExterior: true,
    mustConnectTo: [],
    preferConnectTo: ['living_room', 'lounge', 'corridor'],
    avoidOnlyAccessFrom: [],
    windowRequired: true,
    circulationPriority: 3
  },
  stairs: {
    label: '楼梯',
    minArea: 8.64,
    maxArea: 15,
    minWidth: 2.4,
    minDepth: 3.6,
    idealWidthRange: [2.4, 3.0],
    idealDepthRange: [3.6, 5.4],
    maxAspectRatio: 2,
    mustTouchExterior: false,
    preferTouchExterior: false,
    mustConnectTo: ['living_room', 'lounge', 'corridor'],
    preferConnectTo: ['entrance'],
    avoidOnlyAccessFrom: ['bedroom'],
    windowRequired: false,
    circulationPriority: 10
  },
  corridor: {
    label: '过道',
    minArea: 2,
    maxArea: 8,
    minWidth: 0.9,
    minDepth: 2.0,
    idealWidthRange: [0.9, 1.4],
    idealDepthRange: [2.0, 6.0],
    maxAspectRatio: 5,
    mustTouchExterior: false,
    preferTouchExterior: false,
    mustConnectTo: [],
    preferConnectTo: ['living_room', 'lounge', 'bedroom', 'bathroom'],
    avoidOnlyAccessFrom: [],
    windowRequired: false,
    circulationPriority: 9
  },
  storage: {
    label: '储藏间',
    minArea: 3,
    maxArea: 8,
    minWidth: 1.8,
    minDepth: 2.0,
    idealWidthRange: [1.8, 2.6],
    idealDepthRange: [2.0, 3.2],
    maxAspectRatio: 3,
    mustTouchExterior: false,
    preferTouchExterior: false,
    mustConnectTo: [],
    preferConnectTo: ['corridor', 'living_room'],
    avoidOnlyAccessFrom: [],
    windowRequired: false,
    circulationPriority: 2
  },
  lounge: {
    label: '起居厅',
    minArea: 15,
    maxArea: 35,
    minWidth: 3.6,
    minDepth: 4.2,
    idealWidthRange: [3.8, 5.2],
    idealDepthRange: [4.2, 6.0],
    maxAspectRatio: 3,
    mustTouchExterior: false,
    preferTouchExterior: true,
    mustConnectTo: ['stairs'],
    preferConnectTo: ['corridor', 'bedroom'],
    avoidOnlyAccessFrom: [],
    windowRequired: true,
    circulationPriority: 10
  },
  terrace: {
    label: '露台',
    minArea: 6,
    maxArea: 25,
    minWidth: 2.0,
    minDepth: 3.0,
    idealWidthRange: [2.0, 4.0],
    idealDepthRange: [3.0, 5.0],
    maxAspectRatio: 4,
    mustTouchExterior: true,
    preferTouchExterior: true,
    mustConnectTo: [],
    preferConnectTo: ['living_room', 'lounge', 'bedroom'],
    avoidOnlyAccessFrom: [],
    windowRequired: false,
    circulationPriority: 1
  }
};

export function getRoomRule(type) {
  return ROOM_RULES[type] || null;
}

