-- 小组/个人私有 GLB 模型库、建筑绑定与只追加操作日志。
-- 可重复执行；依赖 profiles、group_memberships、planning_spaces 及身份辅助函数。

create table if not exists public.group_model_assets (
  id uuid primary key,
  name text not null check (length(trim(name)) between 1 and 100),
  storage_path text not null unique,
  file_size bigint not null check (file_size > 0 and file_size <= 52428800),
  mime_type text not null default 'model/gltf-binary' check (mime_type = 'model/gltf-binary'),
  scope_kind text not null check (scope_kind in ('group', 'personal')),
  course_id text,
  group_id text references public.course_groups(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  source_space_id text,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  check (
    (scope_kind = 'group' and group_id is not null)
    or (scope_kind = 'personal' and group_id is null and owner_id = created_by)
  )
);

create table if not exists public.building_model_bindings (
  id bigint generated by default as identity primary key,
  space_id text not null,
  object_code text not null,
  asset_id uuid not null references public.group_model_assets(id) on delete restrict,
  scope_kind text not null check (scope_kind in ('group', 'personal')),
  group_id text references public.course_groups(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  transform jsonb not null default '{}'::jsonb,
  updated_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (space_id, object_code)
);

create table if not exists public.model_operation_events (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  actor_id uuid not null references auth.users(id),
  actor_name text not null default '',
  action text not null check (action in ('upload', 'replace', 'restore_white', 'delete')),
  result text not null default 'success',
  scope_kind text not null check (scope_kind in ('group', 'personal')),
  course_id text,
  group_id text,
  owner_id uuid not null references auth.users(id),
  space_id text,
  object_code text,
  asset_id uuid,
  asset_name text,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists idx_group_model_assets_group_created
  on public.group_model_assets(group_id, created_at desc);
create index if not exists idx_group_model_assets_owner_created
  on public.group_model_assets(owner_id, created_at desc);
create index if not exists idx_building_model_bindings_asset
  on public.building_model_bindings(asset_id);
create index if not exists idx_model_operation_events_scope_time
  on public.model_operation_events(group_id, owner_id, occurred_at desc);

create or replace function public.can_access_model_scope(
  p_scope_kind text,
  p_group_id text,
  p_owner_id uuid
)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select auth.uid() is not null and (
    public.current_profile_role() = 'admin'
    or (p_scope_kind = 'personal' and p_owner_id = auth.uid())
    or (
      p_scope_kind = 'group'
      and p_group_id is not null
      and exists (
        select 1
        from public.group_memberships membership
        where membership.group_id = p_group_id
          and membership.student_key = public.current_profile_student_key()
      )
    )
  );
$$;

revoke all on function public.can_access_model_scope(text, text, uuid) from public, anon;
grant execute on function public.can_access_model_scope(text, text, uuid) to authenticated;

alter table public.group_model_assets enable row level security;
alter table public.building_model_bindings enable row level security;
alter table public.model_operation_events enable row level security;

drop policy if exists group_model_assets_select_scope on public.group_model_assets;
create policy group_model_assets_select_scope on public.group_model_assets
for select to authenticated
using (public.can_access_model_scope(scope_kind, group_id, owner_id));

drop policy if exists building_model_bindings_select_scope on public.building_model_bindings;
create policy building_model_bindings_select_scope on public.building_model_bindings
for select to authenticated
using (public.can_access_model_scope(scope_kind, group_id, owner_id));

drop policy if exists model_operation_events_select_scope on public.model_operation_events;
create policy model_operation_events_select_scope on public.model_operation_events
for select to authenticated
using (public.can_access_model_scope(scope_kind, group_id, owner_id));

-- 写操作只允许经过下面的原子 RPC，避免绕过校验或遗漏日志。
revoke all on table public.group_model_assets from anon, authenticated;
revoke all on table public.building_model_bindings from anon, authenticated;
revoke all on table public.model_operation_events from anon, authenticated;
grant select on table public.group_model_assets to authenticated;
grant select on table public.building_model_bindings to authenticated;
grant select on table public.model_operation_events to authenticated;

create or replace function public.prevent_model_event_mutation()
returns trigger
language plpgsql
as $$
begin
  raise exception 'MODEL_OPERATION_EVENTS_ARE_APPEND_ONLY';
end;
$$;

drop trigger if exists model_operation_events_no_update on public.model_operation_events;
create trigger model_operation_events_no_update
before update on public.model_operation_events
for each row execute function public.prevent_model_event_mutation();

drop trigger if exists model_operation_events_no_delete on public.model_operation_events;
create trigger model_operation_events_no_delete
before delete on public.model_operation_events
for each row execute function public.prevent_model_event_mutation();

create or replace function public.register_group_model(
  p_asset_id uuid,
  p_name text,
  p_storage_path text,
  p_file_size bigint,
  p_scope_kind text,
  p_group_id text default null,
  p_course_id text default null,
  p_space_id text default null
)
returns public.group_model_assets
language plpgsql
security definer
set search_path = public, storage, pg_temp
as $$
declare
  v_asset public.group_model_assets;
  v_name text := left(trim(coalesce(p_name, '')), 100);
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  if p_scope_kind not in ('group', 'personal') then raise exception 'INVALID_SCOPE'; end if;
  if p_file_size <= 0 or p_file_size > 52428800 then raise exception 'INVALID_FILE_SIZE'; end if;
  if p_storage_path !~ '\.glb$' then raise exception 'GLB_REQUIRED'; end if;
  if v_name = '' then raise exception 'MODEL_NAME_REQUIRED'; end if;
  if not public.can_access_model_scope(p_scope_kind, p_group_id, auth.uid()) then
    raise exception 'MODEL_SCOPE_FORBIDDEN';
  end if;

  insert into public.group_model_assets(
    id, name, storage_path, file_size, scope_kind, course_id, group_id,
    owner_id, source_space_id, created_by
  ) values (
    p_asset_id, v_name, p_storage_path, p_file_size, p_scope_kind, p_course_id,
    case when p_scope_kind = 'group' then p_group_id else null end,
    auth.uid(), p_space_id, auth.uid()
  ) returning * into v_asset;

  insert into public.model_operation_events(
    actor_id, actor_name, action, scope_kind, course_id, group_id, owner_id,
    space_id, asset_id, asset_name, metadata
  ) values (
    auth.uid(), coalesce(public.current_profile_display_name(), ''), 'upload',
    v_asset.scope_kind, v_asset.course_id, v_asset.group_id, v_asset.owner_id,
    v_asset.source_space_id, v_asset.id, v_asset.name,
    jsonb_build_object('storage_path', v_asset.storage_path, 'file_size', v_asset.file_size)
  );

  return v_asset;
end;
$$;

create or replace function public.place_group_model(
  p_asset_id uuid,
  p_space_id text,
  p_object_code text,
  p_transform jsonb default '{}'::jsonb
)
returns public.building_model_bindings
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_asset public.group_model_assets;
  v_binding public.building_model_bindings;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  if trim(coalesce(p_space_id, '')) = '' or trim(coalesce(p_object_code, '')) = '' then
    raise exception 'BUILDING_IDENTITY_REQUIRED';
  end if;

  select * into v_asset from public.group_model_assets where id = p_asset_id;
  if not found then raise exception 'MODEL_NOT_FOUND'; end if;
  if not public.can_access_model_scope(v_asset.scope_kind, v_asset.group_id, v_asset.owner_id) then
    raise exception 'MODEL_SCOPE_FORBIDDEN';
  end if;
  if v_asset.scope_kind = 'group' and not exists (
    select 1 from public.planning_spaces ps
    where ps.id = p_space_id and ps.group_id = v_asset.group_id
  ) then
    raise exception 'MODEL_SPACE_SCOPE_MISMATCH';
  end if;
  if v_asset.scope_kind = 'personal' and not exists (
    select 1 from public.course_personal_spaces personal_space
    where personal_space.id::text = p_space_id
      and personal_space.owner_id = auth.uid()
  ) then
    raise exception 'MODEL_SPACE_FORBIDDEN';
  end if;

  insert into public.building_model_bindings(
    space_id, object_code, asset_id, scope_kind, group_id, owner_id, transform, updated_by
  ) values (
    p_space_id, trim(p_object_code), v_asset.id, v_asset.scope_kind,
    v_asset.group_id, v_asset.owner_id, coalesce(p_transform, '{}'::jsonb), auth.uid()
  )
  on conflict (space_id, object_code) do update set
    asset_id = excluded.asset_id,
    scope_kind = excluded.scope_kind,
    group_id = excluded.group_id,
    owner_id = excluded.owner_id,
    transform = excluded.transform,
    updated_by = auth.uid(),
    updated_at = now()
  returning * into v_binding;

  insert into public.model_operation_events(
    actor_id, actor_name, action, scope_kind, course_id, group_id, owner_id,
    space_id, object_code, asset_id, asset_name, metadata
  ) values (
    auth.uid(), coalesce(public.current_profile_display_name(), ''), 'replace',
    v_asset.scope_kind, v_asset.course_id, v_asset.group_id, v_asset.owner_id,
    p_space_id, trim(p_object_code), v_asset.id, v_asset.name,
    jsonb_build_object('transform', coalesce(p_transform, '{}'::jsonb))
  );

  return v_binding;
end;
$$;

create or replace function public.restore_building_white_model(
  p_space_id text,
  p_object_code text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_binding public.building_model_bindings;
  v_asset public.group_model_assets;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  select * into v_binding
  from public.building_model_bindings
  where space_id = p_space_id and object_code = trim(p_object_code)
  for update;

  if found then
    if not public.can_access_model_scope(v_binding.scope_kind, v_binding.group_id, v_binding.owner_id) then
      raise exception 'MODEL_SCOPE_FORBIDDEN';
    end if;
    select * into v_asset from public.group_model_assets where id = v_binding.asset_id;
    delete from public.building_model_bindings where id = v_binding.id;
  else
    if exists (
      select 1 from public.course_personal_spaces personal_space
      where personal_space.id::text = p_space_id and personal_space.owner_id = auth.uid()
    ) then
      v_binding.scope_kind := 'personal';
      v_binding.owner_id := auth.uid();
    elsif exists (
      select 1 from public.planning_spaces group_space
      where group_space.id = p_space_id
        and group_space.group_id is not null
        and public.can_access_model_scope('group', group_space.group_id, auth.uid())
    ) then
      select group_space.group_id into v_binding.group_id
      from public.planning_spaces group_space where group_space.id = p_space_id;
      v_binding.scope_kind := 'group';
      v_binding.owner_id := auth.uid();
    else
      raise exception 'MODEL_SPACE_FORBIDDEN';
    end if;
  end if;

  insert into public.model_operation_events(
    actor_id, actor_name, action, scope_kind, course_id, group_id, owner_id,
    space_id, object_code, asset_id, asset_name
  ) values (
    auth.uid(), coalesce(public.current_profile_display_name(), ''), 'restore_white',
    v_binding.scope_kind, v_asset.course_id, v_binding.group_id, v_binding.owner_id,
    p_space_id, trim(p_object_code), v_binding.asset_id, v_asset.name
  );

  return jsonb_build_object('restored', true);
end;
$$;

create or replace function public.delete_group_model(p_asset_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_asset public.group_model_assets;
  v_usage_count integer;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  select * into v_asset from public.group_model_assets where id = p_asset_id for update;
  if not found then raise exception 'MODEL_NOT_FOUND'; end if;
  if not public.can_access_model_scope(v_asset.scope_kind, v_asset.group_id, v_asset.owner_id) then
    raise exception 'MODEL_SCOPE_FORBIDDEN';
  end if;

  select count(*) into v_usage_count
  from public.building_model_bindings
  where asset_id = p_asset_id;
  if v_usage_count > 0 then raise exception 'MODEL_IN_USE:%', v_usage_count; end if;

  insert into public.model_operation_events(
    actor_id, actor_name, action, scope_kind, course_id, group_id, owner_id,
    space_id, asset_id, asset_name, metadata
  ) values (
    auth.uid(), coalesce(public.current_profile_display_name(), ''), 'delete',
    v_asset.scope_kind, v_asset.course_id, v_asset.group_id, v_asset.owner_id,
    v_asset.source_space_id, v_asset.id, v_asset.name,
    jsonb_build_object('storage_path', v_asset.storage_path)
  );

  delete from public.group_model_assets where id = p_asset_id;
  return jsonb_build_object('deleted', true, 'storage_path', v_asset.storage_path);
end;
$$;

revoke all on function public.register_group_model(uuid, text, text, bigint, text, text, text, text) from public, anon;
revoke all on function public.place_group_model(uuid, text, text, jsonb) from public, anon;
revoke all on function public.restore_building_white_model(text, text) from public, anon;
revoke all on function public.delete_group_model(uuid) from public, anon;
grant execute on function public.register_group_model(uuid, text, text, bigint, text, text, text, text) to authenticated;
grant execute on function public.place_group_model(uuid, text, text, jsonb) to authenticated;
grant execute on function public.restore_building_white_model(text, text) to authenticated;
grant execute on function public.delete_group_model(uuid) to authenticated;

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values ('group-models', 'group-models', false, 52428800, array['model/gltf-binary', 'application/octet-stream'])
on conflict (id) do update set
  public = false,
  file_size_limit = 52428800,
  allowed_mime_types = array['model/gltf-binary', 'application/octet-stream'];

drop policy if exists group_models_storage_select on storage.objects;
create policy group_models_storage_select on storage.objects
for select to authenticated
using (
  bucket_id = 'group-models'
  and (
    public.current_profile_role() = 'admin'
    or (split_part(name, '/', 1) = 'users' and split_part(name, '/', 2) = auth.uid()::text)
    or (
      split_part(name, '/', 1) = 'groups'
      and exists (
        select 1 from public.group_memberships membership
        where membership.group_id = split_part(name, '/', 2)
          and membership.student_key = public.current_profile_student_key()
      )
    )
  )
);

drop policy if exists group_models_storage_insert on storage.objects;
create policy group_models_storage_insert on storage.objects
for insert to authenticated
with check (
  bucket_id = 'group-models'
  and lower(storage.extension(name)) = 'glb'
  and (
    public.current_profile_role() = 'admin'
    or (split_part(name, '/', 1) = 'users' and split_part(name, '/', 2) = auth.uid()::text)
    or (
      split_part(name, '/', 1) = 'groups'
      and exists (
        select 1 from public.group_memberships membership
        where membership.group_id = split_part(name, '/', 2)
          and membership.student_key = public.current_profile_student_key()
      )
    )
  )
);

drop policy if exists group_models_storage_delete on storage.objects;
create policy group_models_storage_delete on storage.objects
for delete to authenticated
using (
  bucket_id = 'group-models'
  and (
    public.current_profile_role() = 'admin'
    or (split_part(name, '/', 1) = 'users' and split_part(name, '/', 2) = auth.uid()::text)
    or (
      split_part(name, '/', 1) = 'groups'
      and exists (
        select 1 from public.group_memberships membership
        where membership.group_id = split_part(name, '/', 2)
          and membership.student_key = public.current_profile_student_key()
      )
    )
  )
);
