-- 留言表：按对象编码 + 对象类型存储多身份发言
create table if not exists public.object_comments (
  id bigint generated by default as identity primary key,
  object_code text not null,
  object_type text not null,
  author_name text not null,
  content text not null check (char_length(content) between 1 and 200),
  created_at timestamptz not null default now()
);

create index if not exists idx_object_comments_object on public.object_comments (object_type, object_code, created_at desc);

alter table public.object_comments enable row level security;

-- 你当前是前端匿名 key 直接访问，示例策略放开读写（教学场景）
drop policy if exists "object_comments_select_all" on public.object_comments;
create policy "object_comments_select_all"
on public.object_comments
for select
to anon, authenticated
using (true);

drop policy if exists "object_comments_insert_all" on public.object_comments;
create policy "object_comments_insert_all"
on public.object_comments
for insert
to anon, authenticated
with check (true);
