-- 任务驱动课程工作台：课程、小组、任务进度与只追加操作日志
-- 本脚本可重复执行，不删除现有平台表或数据。

create table if not exists public.courses (
  id text primary key,
  title text not null,
  village_id text not null,
  stages jsonb not null default '[]'::jsonb,
  tasks jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.course_groups (
  id text primary key,
  course_id text not null references public.courses(id) on delete cascade,
  name text not null,
  join_code text not null unique,
  locked boolean not null default false,
  space_id text,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.group_memberships (
  id bigint generated by default as identity primary key,
  course_id text not null references public.courses(id) on delete cascade,
  group_id text not null references public.course_groups(id) on delete cascade,
  student_key text not null,
  student_name text not null,
  student_id text,
  role text not null default 'member' check (role in ('member', 'leader')),
  joined_at timestamptz not null default now(),
  unique (course_id, student_key)
);

create table if not exists public.task_progress (
  id bigint generated by default as identity primary key,
  course_id text not null references public.courses(id) on delete cascade,
  student_key text not null,
  group_id text,
  task_id text not null,
  completed boolean not null default false,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (course_id, student_key, task_id)
);

create table if not exists public.activity_events (
  event_id text primary key,
  client_event_id text not null unique,
  occurred_at timestamptz not null default now(),
  student_key text,
  student_name text,
  course_id text,
  group_id text,
  task_id text,
  space_id text,
  action text not null,
  target_type text,
  target_id text,
  view_mode text,
  metadata jsonb not null default '{}'::jsonb
);

-- 将现有规划空间与课程、小组关联；保留原有空间数据与使用方式。
alter table public.planning_spaces
  add column if not exists course_id text;
alter table public.planning_spaces
  add column if not exists group_id text;
alter table public.planning_spaces
  add column if not exists space_type text;

create index if not exists idx_course_groups_course_id
  on public.course_groups(course_id);
create index if not exists idx_group_memberships_group_id
  on public.group_memberships(group_id);
create index if not exists idx_group_memberships_student_key
  on public.group_memberships(student_key);
create index if not exists idx_task_progress_course_student
  on public.task_progress(course_id, student_key);
create index if not exists idx_activity_events_course_time
  on public.activity_events(course_id, occurred_at desc);
create index if not exists idx_activity_events_group_time
  on public.activity_events(group_id, occurred_at desc);
create index if not exists idx_activity_events_student_time
  on public.activity_events(student_key, occurred_at desc);
create index if not exists idx_activity_events_action
  on public.activity_events(action);
create index if not exists idx_planning_spaces_course_group
  on public.planning_spaces(course_id, group_id);

insert into public.courses (id, title, village_id, stages, tasks)
values (
  'mibu-village-planning',
  '米埗村规划实践',
  'mibu',
  '[
    {"key":"group_join","title":"加入小组","taskIds":["join-group"]},
    {"key":"learning","title":"学习准备","taskIds":["learning-ready"]},
    {"key":"figure_ground","title":"图底生产","taskIds":["figure-ground-compose"]},
    {"key":"survey","title":"调研采集","taskIds":["survey-collect"]},
    {"key":"diagnosis","title":"现状诊断","taskIds":["diagnosis-list"]},
    {"key":"design","title":"方案设计","taskIds":["design-workspace"]},
    {"key":"review","title":"协作评审","taskIds":["review-plan"]},
    {"key":"submission","title":"成果提交","taskIds":["submit-result"]}
  ]'::jsonb,
  '[
    {"id":"join-group","stageKey":"group_join","title":"加入课程小组","action":"join_group"},
    {"id":"learning-ready","stageKey":"learning","title":"确认完成学习准备","action":"confirm_learning"},
    {"id":"figure-ground-compose","stageKey":"figure_ground","title":"个人图底生产与合成","action":"open_geoprocessing"},
    {"id":"survey-collect","stageKey":"survey","title":"整理调研照片与备注","action":"open_survey"},
    {"id":"diagnosis-list","stageKey":"diagnosis","title":"形成现状问题清单","action":"open_diagnosis"},
    {"id":"design-workspace","stageKey":"design","title":"编辑小组规划方案","action":"open_workspace"},
    {"id":"review-plan","stageKey":"review","title":"开展小组协作评审","action":"open_review"},
    {"id":"submit-result","stageKey":"submission","title":"提交小组成果","action":"open_submission"}
  ]'::jsonb
)
on conflict (id) do update set
  title = excluded.title,
  village_id = excluded.village_id,
  stages = excluded.stages,
  tasks = excluded.tasks,
  updated_at = now();

alter table public.courses enable row level security;
alter table public.course_groups enable row level security;
alter table public.group_memberships enable row level security;
alter table public.task_progress enable row level security;
alter table public.activity_events enable row level security;

-- 当前项目使用匿名 Supabase 客户端与自建学生账号，因此首期保持与现有表一致的公开访问方式。
-- 后续接入 Supabase Auth 后，应替换为按教师、学生和小组成员限制的策略。
drop policy if exists "course workbench public access" on public.courses;
create policy "course workbench public access" on public.courses
  for all to public using (true) with check (true);

drop policy if exists "course groups public access" on public.course_groups;
create policy "course groups public access" on public.course_groups
  for all to public using (true) with check (true);

drop policy if exists "group memberships public access" on public.group_memberships;
create policy "group memberships public access" on public.group_memberships
  for all to public using (true) with check (true);

drop policy if exists "task progress public access" on public.task_progress;
create policy "task progress public access" on public.task_progress
  for all to public using (true) with check (true);

drop policy if exists "activity events public access" on public.activity_events;
create policy "activity events public access" on public.activity_events
  for all to public using (true) with check (true);
